name: continuous-integration

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: pre-commit/action@v2.0.0

  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    steps:
      - uses: actions/checkout@v2

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge

      - name: Install python dependencies
        run: |
          conda install -y rdkit
          pip install -e .[dev,full]

      - name: Create MongoDB Docker container
        id: build_mongo_docker
        uses: DigiPie/mongo-action@v1.0.1
        with:
          image-version: latest
          port: 27017

      - name: Run pytest
        run: pytest --cov=mincepy_sci -sv -p no:nb_regression test

      - name: Create xml coverage
        run: coverage xml

      - name: Upload coverage to Codecov
        if: github.repository == 'muhrin/mincepy_sci'
        uses: codecov/codecov-action@v1
        with:
            file: ./coverage.xml
            name: mincepy-sci
